### PR TITLE
Updated Login Screen, Privly Applications Repo. 

### PR DESCRIPTION
**Pull request by vshivam**
@smcgregor @gitanshu This is what the new Login Screen looks like. 
login_screenshot

### CODE REVIEW

**Comment by smcgregor** [comment]
This looks better, but the "sign up" link needs to be larger and better differentiated.

**Comment by vshivam** [comment]
How about this ?

screenshot_2015-03-02-13-47-16

**Comment by smcgregor** [comment]
I think this is good. A good activity for new contributors may be to make it better. It is now 90% of the way there, but that last 10% takes a lot more time.

**Comment by gitanshu** [comment]
You should call updateContentServerViews(); in onCreate of LoginActivity so that the app remembers the last set content server. 
Also, I think we should remove Change content server option from settings as it is now available on the login page itself. What do you think? If not, then the consistency between the 2 needs to be fixed as the settings options picks up the url from preference manager as of now. Let me know if you want me to remove it or fix it.

**Comment by vshivam** [comment]
private void updateContentServerViews() {
        contentServerTextView.setText("Logging in to " + mValues.getContentServer() + ".\nTap here to change");
        contentServerEditText.setText(mValues.getContentServer());
    }

The method just updates the values in the textview and edittext of the ViewSwitcher. What's the 'last set content server' that we need to remember ?

Regarding the preference activity, it needs an overhaul. It should be easy enough to replicate the ViewSwitcher approach even in the preference activity for the content server. 

Issue here  : https://github.com/privly/privly-android/issues/37

**Pull request merged**
