### PR TITLE
Crazy amount of Refactor.

### PR DESCRIPTION
**Pull request by vshivam**
* Nav Drawer Refactor. 
* Added one fragment class for PrivlyApplications (Message, PlainPost and History)
* Removed unused drawables. 
* Updated way of Fragments backstack handling.

### CODE REVIEW

**Comment by vshivam** [comment]
@gitanshu reverted back to mipmap for launcher icon.

**Comment by vshivam** [comment]
@gitanshu Also if there are no issues, I am going to merge this into the gradle branch and then merge the gradle branch to master. People are getting confused as to which branch they should use and there's no point keeping two versions one of which is completely lagging behind.

**Comment by gitanshu** [comment]
@vshivam That's exactly what I have been thinking since we decided to keep 2 branches. It'd be great if you merge it to master.

**Comment by vshivam** [comment]
Alright. Here we go then.

**Pull request merged**
